version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - .env
  backend:
    build: ./backend
    network_mode: "host"
    volumes:
      - ./images:/images
    env_file:
      - .env
